steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/reboot-repo-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/reboot-repo-image']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'jobs', 'deploy', 'reboot-repo-job',
        '--image', 'gcr.io/$PROJECT_ID/reboot-repo-image',
        '--region', 'europe-west2',
        # '--command', '/your/entrypoint/script', # Optional: override entrypoint
        # '--args', 'arg1,arg2',                  # Optional: arguments to the entrypoint
        # '--max-retries', '1',                   # Number of max retries (optional)
        # '--execute-now',                        # Automatically execute after deploy
        '--project', '$PROJECT_ID'
      ]


  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'jobs', 'execute', 'reboot-repo-job',
        '--region', 'europe-west2',
        '--project', '$PROJECT_ID'
      ]
options:
  logging: CLOUD_LOGGING_ONLY