steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ltc-reboot25-team-60/react-static', '.']

images:
  - 'gcr.io/ltc-reboot25-team-60/react-static'

options:
  logging: CLOUD_LOGGING_ONLY

