INSERT INTO `core_data.account_details`
SELECT
  FORMAT('ACCT%08d', n) AS account_id,
  FORMAT('CUST%07d', 1 + MOD(n, 5000000)) AS customer_id,
  FORMAT('0011%08d', n) AS account_number,
  ['SAVINGS','CURRENT','SALARY','NRI','LOAN'][ORDINAL(1 + CAST(RAND()*4 AS INT64))] AS account_type,
  DATE_SUB(CURRENT_DATE(), INTERVAL CAST(RAND()*3650 AS INT64) DAY) AS open_date,
  FORMAT('BR%03d', 1 + MOD(n, 1000)) AS branch_code,
  CONCAT('Branch ', CAST(1 + MOD(n,1000) AS STRING)) AS branch_name,
  CAST(1000 + RAND()*999999 AS FLOAT64) AS balance,
  CAST(500 + RAND()*900000 AS FLOAT64) AS available_balance,
  ['INR','USD','GBP','EUR','SGD'][ORDINAL(1 + CAST(RAND()*4 AS INT64))] AS currency,
  ['active','dormant','closed'][ORDINAL(1 + CAST(RAND()*2 AS INT64))] AS status,
  ROUND(RAND()*5, 2) AS interest_rate,
  ROUND(RAND()*10000, 2) AS overdraft_limit,
  CAST(RAND() > 0.7 AS BOOL) AS is_salary_account,
  CAST(RAND() > 0.8 AS BOOL) AS joint_account,
  CONCAT('Nominee', n) AS nominee_name,
  ['Father','Mother','Spouse','Sibling','Friend'][ORDINAL(1 + CAST(RAND()*4 AS INT64))] AS nominee_relation,
  ['verified','pending','rejected'][ORDINAL(1 + CAST(RAND()*2 AS INT64))] AS kyc_status,
  DATE_SUB(CURRENT_DATE(), INTERVAL CAST(RAND()*1500 AS INT64) DAY) AS kyc_update_date,
  DATE_SUB(CURRENT_DATE(), INTERVAL CAST(RAND()*600 AS INT64) DAY) AS last_deposit_date,
  DATE_SUB(CURRENT_DATE(), INTERVAL CAST(RAND()*600 AS INT64) DAY) AS last_withdrawal_date,
  CAST(100000 + RAND()*8500000 AS FLOAT64) AS total_deposits,
  CAST(50000 + RAND()*6000000 AS FLOAT64) AS total_withdrawals,
  CONCAT('Mgr', CAST(1 + MOD(n,500) AS STRING)) AS account_manager,
  NULL AS closed_date,
  ['branch','online','callcenter','mobile'][ORDINAL(1 + CAST(RAND()*3 AS INT64))] AS channel_opened,
  CURRENT_TIMESTAMP() AS created_at,
  CURRENT_TIMESTAMP() AS updated_at
FROM UNNEST(GENERATE_ARRAY(1, 1000000)) AS n;
