INSERT INTO `core_data.transaction_details`
SELECT
  FORMAT('TXN%09d', n) AS txn_id,
  FORMAT('ACCT%08d', 1 + MOD(n, 5000000)) AS account_id,
  FORMAT('CUST%07d', 1 + MOD(n, 5000000)) AS customer_id,
  DATE_SUB(CURRENT_DATE(), INTERVAL CAST(RAND()*3650 AS INT64) DAY) AS transaction_date,
  TIME(CAST(FLOOR(RAND()*24) AS INT64), CAST(FLOOR(RAND()*60) AS INT64), CAST(FLOOR(RAND()*60) AS INT64)) AS transaction_time,
  ['DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'PAYMENT', 'REVERSAL'][ORDINAL(1 + CAST(RAND()*4 AS INT64))] AS transaction_type,
  ROUND(CAST(100 + RAND()*9900 AS FLOAT64), 2) AS transaction_amount,
  ROUND(CAST(500 + RAND()*9900 AS FLOAT64), 2) AS balance_after_txn,
  CONCAT('Description ', n) AS description,
  ['ATM','ONLINE','BRANCH','MOBILE'][ORDINAL(1 + CAST(RAND()*3 AS INT64))] AS channel,
  ['SUCCESS','FAILED','REVERTED'][ORDINAL(1 + CAST(RAND()*2 AS INT64))] AS status,
  CONCAT('user', CAST(1 + MOD(n, 1000000) AS STRING)) AS initiated_by,
  CONCAT('manager', CAST(1 + MOD(n, 100000) AS STRING)) AS approved_by,
  FORMAT('REF%09d', n) AS ref_number,
  CAST(RAND()>0.95 AS BOOL) AS is_reversal,
  CONCAT('City', CAST(1 + MOD(n, 30) AS STRING)) AS location,
  FORMAT('DEV%06d', 1+MOD(n,1000000)) AS device_id,
  ['INR','USD','GBP','EUR','SGD'][ORDINAL(1 + CAST(RAND()*4 AS INT64))] AS currency,
  CONCAT('Merchant', CAST(1 + MOD(n,1000) AS STRING)) AS merchant,
  NULL AS remarks,
  ROUND(RAND()*150, 2) AS fee,
  ROUND(RAND()*50, 2) AS tax,
  ['ATM','NET','POS'][ORDINAL(1+CAST(RAND()*2 AS INT64))] AS txn_medium,
  IF(RAND()>0.8, FORMAT('ATM%06d', 1+MOD(n,10000)), NULL) AS atm_id,
  IF(RAND()>0.95, 'Rev. Reason', NULL) AS reversal_reason,
  CURRENT_TIMESTAMP() AS created_at,
  CURRENT_TIMESTAMP() AS updated_at
FROM UNNEST(GENERATE_ARRAY(1, 1000000)) AS n;
