INSERT INTO `core_data.customer_details` (
  customer_id,
  first_name,
  last_name,
  gender,
  dob,
  email,
  phone,
  address,
  city,
  state,
  postal_code,
  country,
  national_id,
  marital_status,
  occupation,
  company,
  annual_income,
  credit_score,
  preferred_language,
  join_date,
  status,
  last_active,
  marketing_opt_in,
  referred_by,
  consent_email_marketing,
  risk_profile,
  created_at,
  updated_at
)
SELECT
  FORMAT('CUST%07d', n) AS customer_id,
  CONCAT('First', n) AS first_name,
  CONCAT('Last', n) AS last_name,
  ['M', 'F', 'O'][ORDINAL(1 + CAST(RAND()*2 AS INT64))] AS gender,
  DATE_SUB(CURRENT_DATE(), INTERVAL 18 + CAST(RAND()*62 AS INT64) YEAR) AS dob,
  FORMAT('user%07d@example.com', n) AS email,
  FORMAT('+1%09d', CAST(100000000 + n AS INT64)) AS phone,
  CONCAT('Address', n) AS address,
  ['Mumbai','Delhi','Bangalore','Chennai','Kolkata','Pune'][ORDINAL(1 + CAST(RAND()*5 AS INT64))] AS city,
  ['MH','DL','KA','TN','WB','PN'][ORDINAL(1 + CAST(RAND()*5 AS INT64))] AS state,
  FORMAT('%06d', CAST(100000 + MOD(n,900000) AS INT64)) AS postal_code,
  ['IN', 'US', 'UK', 'SG', 'AU'][ORDINAL(1 + CAST(RAND()*4 AS INT64))] AS country,
  FORMAT('NID%09d', CAST(100000000+n AS INT64)) AS national_id,
  ['Single','Married','Other'][ORDINAL(1 + CAST(RAND()*2 AS INT64))] AS marital_status,
  ['Engineer','Doctor','Teacher','Business','Other'][ORDINAL(1 + CAST(RAND()*4 AS INT64))] AS occupation,
  CONCAT('Company', CAST(1 + MOD(n, 500) AS STRING)) AS company,
  CAST(200000 + RAND()*8000000 AS FLOAT64) AS annual_income,
  400 + CAST(RAND()*450 AS INT64) AS credit_score,
  ['en','hi','gu','ta','ml'][ORDINAL(1 + CAST(RAND()*4 AS INT64))] AS preferred_language,
  DATE_SUB(CURRENT_DATE(), INTERVAL CAST(RAND()*3650 AS INT64) DAY) AS join_date,
  ['active','suspended','closed'][ORDINAL(1 + CAST(RAND()*2 AS INT64))] AS status,
  DATETIME_SUB(CURRENT_DATETIME(), INTERVAL CAST(RAND()*3650 AS INT64) DAY) AS last_active,
  CAST(RAND() > 0.7 AS BOOL) AS marketing_opt_in,
  FORMAT('CUST%07d', 1 + MOD(n, 1000)) AS referred_by,
  CAST(RAND() > 0.5 AS BOOL) AS consent_email_marketing,
  ['low','medium','high'][ORDINAL(1 + CAST(RAND()*2 AS INT64))] AS risk_profile,
  CURRENT_TIMESTAMP() AS created_at,
  CURRENT_TIMESTAMP() AS updated_at
FROM
  UNNEST(GENERATE_ARRAY(1, 1000000)) AS n;
